### PR TITLE
Use LoadState address that also works for coop

### PR DESCRIPTION
**Pull request by rskuipers**

### CODE REVIEW

**Review by badBlackShark — CHANGES_REQUESTED** [review]
Sorry, this pointer doesn't work for me (at least in singleplayer).

**Comment by rskuipers** [comment]
@badBlackShark Strange. I do have one issue, I have to start a level once, then exit to menu and start again for it to work. After that it continues to work.

**Comment by badBlackShark** [comment]
> 
> 
> @badBlackShark Strange. I do have one issue, I have to start a level once, then exit to menu and start again for it to work. After that it continues to work.

Interesting. Yeah I only tried it once and then discarded it. I'll recheck in a bit.

**Comment by rskuipers** [comment]
Of course that would still make this PR questionable, there might be another address that works for both solo and coop. Maybe leave this PR open until we found a better one.

**Comment by badBlackShark** [comment]
Yeah sounds good. Tbf I don't think anyone but us is using this script anytime soon, so I'm not too concerned about covering all the cases here, since we can both adjust based on what we need.

**Comment by rskuipers** [comment]
@badBlackShark Looks like this one works more consistently, despite having to restart it the first time around. We have 2 new players who couldn't get the original one to work but this version did.

Maybe it's still worth merging this?

**Pull request closed without merging**
